language: java
jdk:
- openjdk8

# avoiding this error : "the job exceeded the maximum log length and has been terminated "
cache: 
  directories:
  - .autoconf
  - $HOME/.m2
services:
- docker

addons:
  sonarcloud:
    organization: "astor-protect-cloud-based-video-surveillance"
    token:
      secure: $SONAR_TOKEN
before_install:
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine
script:
- mvn deploy
- mvn heroku:deploy
after_success:
- mvn site
- bash <(curl -s https://codecov.io/bash)
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

