language : java
jdk:
  - openjdk8
services:
  - docker  

env:
  global:
    - CODECOV_TOKEN=45174070-06b4-44b1-a855-30da3c75c37e
before_install:
  - docker pull openjdk:8-jdk-alpine
  
script:
  
  - mvn install dockerfile:push

after_success:
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash <(curl -s https://codecov.io/bash)
