language : java
jdk:
  - openjdk8
services:
  - docker  

env:
  global:
    - CODECOV_TOKEN=45174070-06b4-44b1-a855-30da3c75c37e
    
before_install:
  - docker pull openjdk:8-jdk-alpine
  
script:
  - mvn site
  - mvn test
  - mvn clean package

after_success:
  
  - bash <(curl -s https://codecov.io/bash)
