language : java
jdk:
  - openjdk8
services:
  - docker  

env:
  global:
    - CODECOV_TOKEN=45174070-06b4-44b1-a855-30da3c75c37e
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine
  
script:
  
  - mvn clean package
  - mvn install dockerfile:build
  - mvn install dockerfile:push
  - docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
  - docker build -t registry.heroku.com/astorprotect/cloud-based-video-surveillance/web .
  - docker push registry.heroku.com/astorprotect/cloud-based-video-surveillance/web


after_success:
  - bash <(curl -s https://codecov.io/bash)
  
# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: astor-protect-cloud-video
  on:
    tags: false
    repo: $IMAGE_NAME
  
