language : java
jdk:
  - openjdk8
services:
  - docker


after_success:
  - bash <(curl -s https://codecov.io/bash)
  
env:
  global:
    - CODECOV_TOKEN=45174070-06b4-44b1-a855-30da3c75c37e
    #DOCKER_USER
    - secure: "m+66dR83RWtzta20ix95h/W3rCg1C5R4yMxyi7nQ7L47pPmIo+deo+FUWRV0fYSN0Q721H8bb/vfMrrpjmaiWrAkgBWAU5Yp/8Y+Nc1yPGsGFiV4LjvbqFmYZy/Q1OegKO4pY0/7IEJhEQIoUOCIJPe/k8ofaV2XSDvtvu3LidRuUBEMMDUr+B3VuobdW+6Ui5qxxuKp5P47Etq6411WmGGqr1SycGL1uFPNmbzECXMYXAfOp4fSGIxh1fJw/BGSOQIsUcVh+hE1uMgUukmjutwUP2NYRSnxngOn3F/y+Y9Ujvguapv/49sJXKoZad5JHIs+eoSILBVybxdiD3KDXwE7mrGz8YeYFK2Citgi/mcqubTKAybi6HVcGvhekm3FUIAEXYyckKHnh9viIyCJY68tlh0poHM3GSVLRDAJZPqR1leu0DnyFcW39M2EB/X/zs2YGV8Y8ZtyVFtdkgd2w+Kt5u//JZRbKVh9RUcC4mRbbvTYJwLOff5zUQZ6DE5XXz1nYxTxBkQpcjdx7tBv6krW86BPu0/WjrRkzBBHJEtYm+T4jg5t4i4E+m85Zex3fCvQdX51ZIYie6uSACvuB0DErR/CChlay1JQqvXdod/xMp87LA9SfGAGUEAc9o2/BOD/dX08hsjCWAj9VkNGUcWq+S4rKH5Sg0FoLovQ6jU="


